.TH NEPOMUKCONTROLLER "1" "2011-01-27" "NepomukController - A systray for controlling Nepomuk"
.SH NAME
nepomukcontroller \- A systray for controlling Nepomuk.

.SH SYNOPSIS
.B nepomukcontroller

.SH DESCRIPTION

.B nepomukcontroller
is a small systray applet that allows you to suspend and
resume the Nepomuk file indexer.

The systray was removed from KDE 4.6 to be ported to a stand-alone app
which was not finished before the feature freeze. Thus, this applet will be
merged back into kdebase for KDE 4.7. In the meantime you can use it from
here.
.SH AUTHOR
.B nepomukcontroller
is developed by Sebastian Trueg <trueg@kde.org>.


This manual page was written by Lisandro Damián Nicanor Pérez Meyer for
the Debian project, but may be used by others.

